{% set version = "0.4.1" %}

package:
  name: timeout-decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/timeout-decorator/timeout-decorator-{{ version }}.tar.gz
  sha256: 1a5e276e75c1c5acbf3cdbd9b5e45d77e1f8626f93e39bd5115d68119171d3c6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - timeout_decorator

about:
  home: https://github.com/pnpnpn/timeout-decorator
  license: MIT
  summary: 'Timeout decorator'

extra:
  recipe-maintainers:
    - ocefpaf
