{% set version = "0.5.0" %}

package:
  name: timeout-decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/timeout-decorator/timeout-decorator-{{ version }}.tar.gz
  sha256: 6a2f2f58db1c5b24a2cc79de6345760377ad8bdc13813f5265f6c3e63d16b3d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - timeout_decorator

about:
  home: https://github.com/pnpnpn/timeout-decorator
  license: MIT
  summary: Timeout decorator

extra:
  recipe-maintainers:
    - ocefpaf
