travis:
  secure:
    BINSTAR_TOKEN: jdzEtr1GXMWmKLMrdQr2QY4GqyjJIbOlMzQTURxN5H1v+/Zer9eud567JJWiyns6+NiTC3t5lPYdV9fA2tk1HRAkJsKU3AdpCD8YAHJxYrMh7+6xY3fl8f9eUDL7KzIaCRCOczwShtmayxiy5cDlICJeJ6+SS31iIlNIqbXvxUO5rAluQVF9vOoiN9AYxgvEx4CIYaqtZcNQqB/fO/tKz4MA6525QiSebejVVypS9axKdtfKmh15uf0WbAiFOFuKYhCI0OCmCi0yiDlEgAf38INvzXdkGtN/VhbCAuIFtFqeEZR8x2ZEx60TrtlqUHBMCH81+ro3Gr+dS9DoZ0ayRdQUiwPcBWKF0baJxZSgSkGifGj4QjzdNN9gXg/fyqQrC9MuTJkK9R4A5u67pMyWXlzRNuOzYq3gh4o5ZtW9rckaiTe9JhR3yI0a6LPUKJ9t5qT+QwqgdkgB62kLysigif8XWhN0d4N7+0L12pd92a5WoVTFCq/XfRVbs+esTPXaE02js7BpuF83qAcByhrJ7JORQCsAq25uS1b9JOiCJo/vpYembTvwQ/fpUdmYUauKQ+4YlufVKI6WfPiPOnATmNVnutYW3s3mtt57bGUPyrYX3fuKWFHi0ihZ159Ny9mzTlGg4bmwNX4aVoh20b9PTXdk24UFeyS2NazrMZ06+3M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
