travis:
  secure:
    BINSTAR_TOKEN: IasD16AlcNe2kwJgFqL8fNo0+AhDErjuJm9V4rI2idCgK1GMZDnL1oYnK664fjPSSZZNdZuJem+QpjF9OwrJ+214wMm8KO0zLAebbXqgi1RqkfxJce0W3uYO5z5kJN279ke006b4r7x3Ydu8QHCNbBtJeOJfPSW7jgjwRXUiTAnzrPdTneKCgAWoigfSmLIbSNQz710WX+v3a+EzsPBkQpODya7OQuB3n2pmA75kTORcysQP81DM/iAjHq3sbiu6RRA48kojtdj8NAbBOdkzeXL5Lo4B7PVGjBoIu/UeTSOCPKTSAHEBVncBq1ejP2FAbyz/KIXKwX+k2jS9M+/Jbh/LoVQbFEgYQsH8ElEvgi90rovaz2TFUWyYd/jTBDSTc9Q+BUoWXZS7vCEucK4Qxcg6hQkWMf5q5wj3+CLO/vU9NsjjUNj7OzA5qcsWXxeZxtVTSg9bDqj5ZMKZE5y/ghcGwz1AzUfIOEhrptQkG4HVvwHb2S6maYi2Oh2FbnGrV9oNf8iQnuMWTEP97/kF+Xp06i8l+cilCvOZVcj+YIceCkHT4ZrnjSQgoaGNw9I3at/8WzJ902n5szc/xuR4f65DfSxhqqTiQviLveX5t7NgQm1mZas/r8AABSDZM/B2R4jvZXn3dmqlJLbKmJ0GM7TIsqwz+Ned47PqtCZ3kJk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
